module.exports = {
  SYNC_META: 'SYNC_META',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  LIST_CUSTOMER: 'LIST_CUSTOMER',
  CUSTOMER_ROOT: 'CUSTOMER_ROOT',
  CUSTOMER_SETTING: 'CUSTOMER_SETTING',
  CUSTOMER_LOG_ANALYSER: 'CUSTOMER_LOG_ANALYSER',
  CUSTOMER_USER_ROOT: 'CUSTOMER_USER_ROOT',
  CUSTOMER_USER_ROOT_SETTING: 'CUSTOMER_USER_ROOT_SETTING',
  CUSTOMER_SUBSCRIPTION_ROOT: 'CUSTOMER_SUBSCRIPTION_ROOT',
  CUSTOMER_SUBSCRIPTION_ROOT_COUPON: 'CUSTOMER_SUBSCRIPTION_ROOT_COUPON',
};
